config/routes.rb
Rails.application.routes.draw do
  get 'bookings/create'
  get 'bookings/show'
  get 'bookings/delete'
  get 'users/edit'
  get 'users/update'
  get 'users/show'
  resources :movables do
    resources :bookings
  end
  resources :bookings, only: :index
  devise_for :users
  root to: "pages#home"
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :movable
  has_many :users, through: :movables
end

app/models/movable.rb
class Movable < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, :description, :min_rent_time, :max_rent_time, :main_image, :stock, :price, :categories, presence: true
  validates :name, length: { in: 6..250 }, uniqueness: true
  validates :categories, inclusion: { in: %w(Armchairs Sofas Chairs Tables Lights Rugs Beds Decorations Plants) }
  has_one_attached :main_image
  has_many_attached :gallery_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true
  has_many :movables, dependent: :destroy # from the provider perspective
  has_many :bookings # from the renter perspective
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

# Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # def new
  #   @booking = Booking.new
  #   @movable = Movable.find(params[:id])
  #   authorize @booking
  # end

  def index
    @booking = policy_scope(Booking)
    sql_query = <<~SQL
      bookings.user_id = :query
      OR movables.user_id = :query
    SQL
    @bookings = Booking.joins(:movable).where(sql_query, query: current_user.id)
    authorize @bookings
  end

  def create
    @movable = Movable.find(params[:movable_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.movable = @movable
    authorize @booking

    respond_to do |format|
      if @booking.save
        format.html { redirect_to bookings_path, notice: "Booking was successfull." }
        format.json { render :show, status: :created, location: @movable }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movable.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
  end


private


def booking_params
  params.require(:booking).permit(:checkin_on, :checkout_on )
end
end

app/controllers/movables_controller.rb
class MovablesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_movable, only: %i[ show edit update destroy ]

  # GET /movables or /movables.json
  def index
    @movable = policy_scope(Movable)
    if params[:categories]
      @movables = Movable.where(categories: params[:categories])
    else
      @movables = Movable.all
    end
  end

  # GET /movables/1 or /movables/1.json
  def show
    authorize @movable
    @booking = Booking.new
    # The `geocoded` scope filters only flats/user with coordinates
    @markers = [
      {
        lat: @movable.user.latitude,
        lng: @movable.user.longitude,
        # info_window: render_to_string(partial: "info_window", locals: { user: @movable.user }),
        # image_url: helpers.asset_url("REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS")
      }]
  end

  # GET /movables/new

  def new
    @movable = Movable.new
    authorize @movable
  end

  # GET /movables/1/edit
  def edit
    authorize @movable
  end

  # POST /movables or /movables.json
  def create
    @movable = Movable.new(movable_params)
    @movable.user = current_user
    authorize @movable

    respond_to do |format|
      if @movable.save
        format.html { redirect_to movable_url(@movable), notice: "Movable was successfully created." }
        format.json { render :show, status: :created, location: @movable }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movables/1 or /movables/1.json
  def update
    authorize @movable
    respond_to do |format|
      if @movable.update(movable_params)
        format.html { redirect_to movable_url(@movable), notice: "Movable was successfully updated." }
        format.json { render :show, status: :ok, location: @movable }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movables/1 or /movables/1.json
  def destroy
    authorize @movable
    @movable.destroy

    respond_to do |format|
      format.html { redirect_to movables_url, notice: "Movable was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movable
      @movable = Movable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movable_params
      params.require(:movable).permit(:name, :description, :min_rent_time, :max_rent_time, :main_image, :stock, :price, :categories, gallery_image: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update ]

  # Structure made by lewagon - Geocode lecture
  def index
    @users = User.all
  end
  # end of index test structure

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # GET /users/1
  def show
    authorize @user
    @movables = Movable.where(user: @user)
    @markers = [
      {
        lat: @user.latitude,
        lng: @user.longitude,
        # info_window: render_to_string(partial: "info_window", locals: { user: @movable.user }),
        # image_url: helpers.asset_url("REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS")
      }]
  end

# PUT /users/1
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "Your profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :photo, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/delete.html.erb
<h1>Bookings#delete</h1>
<p>Find me in app/views/bookings/delete.html.erb</p>

app/views/bookings/index.html.erb
<div class="container">
<h1>My Bookings</h1>
<div class="container bookings-container">
  <div class="row bookings-row">
    <div class="col-sm bookings-header">
      <span>Start Date</span>
    </div>
    <div class="col-sm bookings-header">
      <span>End Date</span>
    </div>
    <div class="col-sm bookings-header">
      <span>Movable</span>
    </div>
    <div class="col-sm bookings-header">
      <span>Client</span>
    </div>
    <div class="col-sm bookings-header">
      <span>Provider</span>
    </div>
  </div>

  <% @bookings.each do |booking| %>
    <div class="row bookings-row">
      <div class="col-sm">
        <%= booking.checkin_on %>
      </div>
      <div class="col-sm">
        <%= booking.checkout_on %>
      </div>
      <div class="col-sm">
        <%= booking.movable.name %>
      </div>
      <div class="col-sm">
        <%= "#{booking.user.first_name} #{booking.user.last_name}" %>
      </div>
      <div class="col-sm">
        <a href="<%= user_path(booking.movable.user) %>"><%= "#{booking.movable.user.first_name} #{booking.movable.user.last_name}" %></a>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movablesbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <!-- Geocode link - made by lewagon - Geocode lecture -->
<link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/movables/_form.html.erb
<%= simple_form_for(@movable) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :min_rent_time %>
    <%= f.input :max_rent_time %>
    <% if @movable.new_record?%>
      <%= f.input :main_image, as: :file %>
      <%= f.input :gallery_image, as: :file, input_html: { multiple: true } %>
    <% end %>
    <%= f.input :stock %>
    <%= f.input :price %>
    <%= f.input :categories, collection: %w(Armchairs Sofas Chairs Tables Lights Rugs Beds Decorations Plants) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "signup-button" %>
  </div>
<% end %>

app/views/movables/_movable.html.erb
<div id="<%= dom_id movable %>">
  <p>
    <strong>Name:</strong>
    <%= movable.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movable.description %>
  </p>

  <p>
    <strong>Min rent time:</strong>
    <%= movable.min_rent_time %>
  </p>

  <p>
    <strong>Max rent time:</strong>
    <%= movable.max_rent_time %>
  </p>

  <p>
    <strong>Main image:</strong>
    <%= movable.main_image %>
  </p>

  <p>
    <strong>Gallery image:</strong>
    <%= movable.gallery_image %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= movable.stock %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= movable.price %>
  </p>

  <p>
    <strong>User:</strong>
    <%= movable.user_id %>
  </p>

  <p>
    <strong>Categories:</strong>
    <%= movable.categories %>
  </p>

</div>

app/views/movables/edit.html.erb
<div class="container">

<h1>Editing movable</h1>

<%= render "form", movable: @movable %>

<br>

<div>
  <%= link_to "Show this movable", @movable %> |
  <%= link_to "Back to movables", movables_path %>
</div>

</div>

app/views/movables/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>

<h1><%= params[:categories] %></h1>

<div class="cards">
  <% @movables.each do |movable| %>
    <a class="card-trip" href="<%= movable_path(movable.id) %>">
      <%= cl_image_tag movable.main_image.key, crop: :fill %>
      <div class="card-trip-infos">
        <div>
          <h2><%= movable.name %></h2>
          <p><%= movable.description.first(15) %></p>
        </div>
        <h2 class="card-trip-pricing"><%= movable.price %> CHF / day</h2>
        <%# <%= cl_image_tag current_user.photo.key, crop: :fill, class: "card-trip-user avatar" %>
        <% if movable.main_image.key %>
          <%= cl_image_tag movable.main_image.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
        <% else %>
          <%= cl_image_tag "https://res.cloudinary.com/ddxqnyga2/image/upload/v1661437338/001-user_vutg9d.png", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
      </div>
    </a>
  <% end %>
</div>
</div>

app/views/movables/new.html.erb
<div class="container">
  <h1>New movable</h1>

  <%= render "form", movable: @movable %>

  <br>

  <div>
    <%= link_to "Back to movables", movables_path %>
  </div>

</div>

app/views/movables/show.html.erb
<div class="container">

<p style="color: green"><%= notice %></p>


<h1><%= @movable.name %></h1>
<div class="row">
    <div class="img col-1">
        <div class="gallery-wall">
        <% @movable.gallery_image.each do |gallery_image| %>
          <%= cl_image_tag gallery_image.key, crop: :fill %>
        <% end %>
        </div>
    </div>
    <div class="main-image col-7">
      <%= cl_image_tag @movable.main_image.key, crop: :fill %>
    </div>
    <div class="col-4">
      <div style="width: 100%; height: 400px;"
        data-controller="map"
        data-map-markers-value="<%= Array(@markers).to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
</div>

  <div class="description container">

    <div class="movable-description">

      <div class="movable-provider">
        <h2 class="movable-h2"><strong>This movable is offered by <%= @movable.user.first_name %></strong></h2>
        <%= cl_image_tag @movable.user.photo.key, class: "avatar" %>
      </div>
      <p>
        <strong><i class="fa-solid fa-clock"></i> Rent time: </strong>
        <%= @movable.min_rent_time.to_i %> - <%= @movable.max_rent_time.to_i %> days
      </p>
        <strong><i class="fa-solid fa-cubes"></i> Stock:</strong>
        <%= @movable.stock %>
      </p>
      <p style="padding-top: 15px;"><%= @movable.description %></p>

    </div>

    <div class="booking-part">
      <p class="movable-price"><%= @movable.price %> CHF / day</p>

      <p class="items-calc"><i class="fa-solid fa-minus" style="margin-right: 15px;"></i> Items <i class="fa-solid fa-plus" style="margin-left: 15px;"></i></p>

        <%= simple_form_for([@movable, @booking]) do |f| %>
          <%= f.input :checkin_on, as: :date, html5: true, label: "From" %>
          <%= f.input :checkout_on, as: :date, html5: true, label: "To" %>
          <%= f.button :submit, class: "btn signup-button" %>
        <% end %>
    </div>

    </div>
    <div>
      <% if policy(@movable).edit? %>
      <%=link_to "Edit this movable", edit_movable_path(@movable) %> |
      <% end %>
      <%= link_to "Back to movables", movables_path %>
      <%= button_to "Destroy this movable", @movable, method: :delete if policy(@movable).destroy? %>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
  <%# banner structure %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661337017/Mood_image-H_eecld9.jpg);">

    <div class="container">
      <h1>for anyone who wants to <strong> furnish </strong></h1>
      <p>with movables you find amazing people who will help you make your environments awesome.</p>
      <%# <a class="btn btn-flat" href="#">Apply now</a> %>
    </div>

  </div>



<%# CATEGORYS: Armchairs Sofas Chairs Tables Lights Rugs Beds Decorations Plants %>
  <%# cards grid structure %>
<div class="cards container">

  <a href="<%= movables_path(categories: "Armchairs") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335387/Armchairs_cbucuk.jpg)">
    Armchairs
  </a>

  <a href="<%= movables_path(categories: "Sofas") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335387/Sofas_rbgfvo.jpg)">
    Sofas
  </a>

    <a href="<%= movables_path(categories: "Chairs") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335388/Chairs_xqhs9t.jpg)">
    Chairs
  </a>

  <a href="<%= movables_path(categories: "Tables") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335388/Tables_fcbtyh.jpg)">
    Tables
  </a>

    <a href="<%= movables_path(categories: "Lights") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335388/Lights_inkwqb.jpg)">
    Lights
  </a>

    <a href="<%= movables_path(categories: "Rugs") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335388/Rugs_kqcnzj.jpg)">
    Tables
  </a>

    <a href="<%= movables_path(categories: "Beds") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335387/Beds_gsy2pn.jpg)">
    Beds
  </a>

    <a href="<%= movables_path(categories: "Decorations") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335388/Decorations_xafdc9.jpg)">
    Decorations
  </a>

    <a href="<%= movables_path(categories: "Plants") %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/ddxqnyga2/image/upload/v1661335388/Plants_iwdssu.jpg)">
    Plants
  </a>
</div>

app/views/shared/_category_template.html.erb
<%# Category Templates - this serve as a template for each card-category %>

<%# Armchairs %>


<%# CATEGORYS: Armchairs Sofas Chairs Tables Lights Rugs Beds Decorations Plants %>
  <%# cards grid structure %>
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/qMny2zc/Armchairs-taylor-vick-Vhbv-P3h-Qwu8-unsplash.jpg)">
    <p> Card 1 </p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/qMny2zc/Armchairs-taylor-vick-Vhbv-P3h-Qwu8-unsplash.jpg)">
    <p> Card 2  </p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/qMny2zc/Armchairs-taylor-vick-Vhbv-P3h-Qwu8-unsplash.jpg)">
    <p> Card 3  </p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/qMny2zc/Armchairs-taylor-vick-Vhbv-P3h-Qwu8-unsplash.jpg)">
    <p> Card 4 </p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/qMny2zc/Armchairs-taylor-vick-Vhbv-P3h-Qwu8-unsplash.jpg)">
    <p> Card 5 </p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/qMny2zc/Armchairs-taylor-vick-Vhbv-P3h-Qwu8-unsplash.jpg)">
    <p> Card 6 </p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <p> Card 7 </p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/qMny2zc/Armchairs-taylor-vick-Vhbv-P3h-Qwu8-unsplash.jpg)">
    <p> Card 8 </p>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/qMny2zc/Armchairs-taylor-vick-Vhbv-P3h-Qwu8-unsplash.jpg)">
    <p> Card 9 </p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/ddxqnyga2/image/upload/v1661337410/Logo_ohvem0.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<%#  %>
<%# <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form> %>
<%#  %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All Movables", movables_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.key == nil %>
              <%= image_tag "https://res.cloudinary.com/ddxqnyga2/image/upload/v1661437338/001-user_vutg9d.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add movable", new_movable_path, class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
 <% if @user == @current_user%>
    <h4> My personal information</h4>
  <% else %>
    <h4> Hi, I'm <%= @user.first_name%></h4>
  <% end %>
  <p>Joined in <%= @user.created_at.year %></p>


  <div class="map-container">
    <div class="edit-part">
      <%= render @user %>
          <% if policy(@user).edit? %>
            <%= link_to "Edit my profile", edit_user_path(@user), class: "edit-button" %>
          <% end %>
    </div>
    <div class="map-profile"
      data-controller="map"
      data-map-markers-value="<%= Array(@markers).to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

<br>

  <% if @user == @current_user%>
    <h4> My listing</h4>
  <% else %>
    <h4> <%= @user.first_name%>'s listing</h4>
  <% end %>


  <div class="cards">
  <% @movables.each do |movable| %>
    <a class="card-trip" href="<%= movable_path(movable.id) %>">
      <%= cl_image_tag movable.main_image.key, crop: :fill %>
      <div class="card-trip-infos">
        <div>
          <h2><%= movable.name %></h2>
          <p><%= movable.description %></p>
        </div>
        <h2 class="card-trip-pricing"><%= movable.price %> CHF / day</h2>
        <%# <%= cl_image_tag current_user.photo.key, crop: :fill, class: "card-trip-user avatar" %>
      </div>
    </a>
  <% end %>
  </div>
</div>